[package]
name = "ghr"
description = "Yet another repository management with auto-attaching profiles."
version = "0.3.4"
license = "MIT"
homepage = "https://github.com/siketyan/ghr"
repository = "https://github.com/siketyan/ghr.git"
readme = "README.md"
rust-version = "1.68.0"
edition = "2021"
authors = [
    "Naoki Ikeguchi <me@s6n.jp>",
]

[dependencies]
anyhow = "1.0"
async-hofs = "0.1.1"
async-trait = "0.1.68"
build-info = "0.0.30"
clap = { version = "4.1", features = ["derive"] }
console = "0.15.2"
dialoguer = "0.10.2"
dirs = "5.0"
git2 = "0.16.1"
itertools = "0.10.5"
indicatif = "0.17.1"
lazy_static = "1.4"
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_regex = "1.1"
serde_with = "2.3"
tokio = { version = "1.26", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.12"
toml = "0.7.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
url = "2.3"
walkdir = "2.3"

gh-config = { version = "0.2.1", optional = true }
octocrab = { version = "0.19.0", optional = true }

[build-dependencies]
build-info-build = "0.0.30"

[features]
default = ["github"]
vendored = ["git2/vendored-libgit2", "git2/vendored-openssl"]
github = ["gh-config", "octocrab"]
